// Generated by Selenium IDE
package pkgSelenium;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TricentisTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
		System.out.println("opening broswer");
		System.setProperty("webdriver.chrome.driver", "C:\\Sleniumsoftwares\\chromedriver107\\chromedriver.exe");
		driver=new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tricentis() throws InterruptedException {
    driver.get("https://demowebshop.tricentis.com/");
    driver.manage().window().setSize(new Dimension(1296, 696));
    driver.findElement(By.linkText("Log in")).click();
    driver.findElement(By.id("Email")).click();
    driver.findElement(By.id("Email")).sendKeys("tsg@gmail.com");
    driver.findElement(By.id("Password")).sendKeys("demo123");
    driver.findElement(By.cssSelector(".login-button")).click();
    //js.executeScript("window.scrollTo(0,136)");
    driver.findElement(By.cssSelector("xpath=//input[@value='Add to cart']")).click();
    driver.findElement(By.id("giftcard_2_RecipientName")).click();
    Thread.sleep(5000);
    driver.findElement(By.xpath("//input[@id=\'giftcard_2_RecipientName\']")).sendKeys("alex");
    driver.findElement(By.id("giftcard_2_RecipientEmail")).click();
    driver.findElement(By.id("giftcard_2_RecipientEmail")).sendKeys("alex@gmail.com");
    driver.findElement(By.id("add-to-cart-button-2")).click();
    Thread.sleep(2000);
    driver.findElement(By.linkText("Log out")).click();
    driver.close();
  }
}
